WEEEEEEEEE.................. [Skendar Keyness]
Fecha: 16/04/2010 || Hora: 09:37:46 p.m. || YO MANDE A UN TORNEO FRACCIONARIO Y Genezaret NO ME HIZO AZUL PARA JUGAR Y DICE "A NO ME ANDA EL COMANDO CALCER 5 MIN. POR MANDAR Y NO SOS AZUL" :|


