SKAD EL GM MAS ESTUPIDO DEL AO [Barditoxc]
Fecha: 16/04/2010 || Hora: 21:14:03 || ES UN IDIOTA TABA HABLANDO CON EL VIENE UNO ME MATA Y LO PUTEO AL LOCO EL ME MANDA A CARCEL Y NO ISE NADA TABA HABLANDO CON SKAD Y ME MATO ESTA PROHIBIDO MATAR A UNO ES UN IDIOTA ME PUSO MEDIA HORA EN CARCEL
